### ISSUE TITLE
Site definition needs to include place_id

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#16]
For google maps to work best, when we launch the browser to a place, we need to use the place ID for best results. Otherwise we are limited to lat/long when will be close but not highlight the destination. Only helps on google maps; no use at all on apple maps.

**Comment by Klaital** [comment]
So this needs to be a separate field entirely, but retaining lat/lon? 

Does Apple have an equivalent? For future proofing, I think we should name the field specifically, like:

    "google_place_id": "ChIJX4k2TVVfXIYRIsTnhA-P-Rc"

I propose that this change should make `google_place_id` override anything submitted in the street/city/state/zip/lat/lon fields, since we can query Google's Places Web Service for details:

https://developers.google.com/places/web-service/details

**Comment by Klaital** [comment]
Added the extra field in klaital/vitasa-web@24121ba81ea7efe5c9dc7d03450eb1413fbdde21

Deployed in staging.

**Comment by Klaital** [comment]
Deployed as well in production. Closing.
