### ISSUE TITLE
GET on /sites returns error 500

### ISSUE THREAD

**Issue by coxthepilot** [coxthepilot/vitasa#35]
Both with and without the token and using different calling methods.

**Comment by Klaital** [comment]
Yeah, that was an issue in the signups query. The bug was in using ```==``` for the equality operator in a SQL query. This is apparently supported in Sqlite3, but not in MySQL. Hence not noticing the bug until production.

I need to set up a MySQL server for staging, so that it can more accurately represent the production environment, as well as writing more automated testing against that environment (the test scripts also use sqlite, and were thus unable to catch this bug)..
